spring:
  profiles: dev

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dvh-kafka-konsument
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

truststore:
  path: ingenting
  password: ingenting

kafka:
  topics: topic1

serviceuser:
  username: ingenting
  password: ingenting

database:
  target:
    jdbcUrl: jdbc:mysql://localhost:3306/dvh_kafka_konsument
    username: root
    password: example
    driverClassName: com.mysql.cj.jdbc.Driver
  mkident:
    jdbcUrl: jdbc:mysql://localhost:3306/dvh_kafka_konsument
    username: root
    password: example
    driverClassName: com.mysql.cj.jdbc.Driver
