spring:
  profile: dev

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dvh-kafka-konsument
      auto-offset-reset: earliest

truststore:
  path: ingenting
  password: ingenting

kafka:
  topics: topic1

serviceuser:
  username: ingenting
  password: ingenting

database:
  target:
    jdbcUrl: jdbc:mysql://localhost:3306/dvh_kafka_konsument
    username: root
    password: example
    driverClassName: com.mysql.cj.jdbc.Driver
  mkident:
    jdbcUrl: jdbc:mysql://localhost:3306/dvh_kafka_konsument
    username: root
    password: example
    driverClassName: com.mysql.cj.jdbc.Driver
